project:
  name: quickstart-rocketmq
  owner: aws-gcr-solutions@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - cn-north-1
  - cn-northwest-1
  s3_bucket: ''
tests:
  rocketmq-cn-north-1-2-AZ:
    parameters:
     AvailabilityZones: cn-north-1a,cn-north-1b
     BrokerClusterCount: '1'
     NumberOfAZs: '2'
     RemoteAccessCIDR: '0.0.0.0/0'
     VolumeSize: '100'
     QSS3BucketName: 'rocketmq-deploy-test-minggu'
     QSS3BucketRegion: 'cn-northwest-1'
     QSS3KeyPrefix: 'rocketmq-'
     KeyPairName: 'rocketMQ'
     NameServerInstanceType: 'm5.large'
     BrokerNodeInstanceType: 'm5.xlarge'
     NameServerClusterCount: '1'
    regions:
      - cn-north-1
    s3_bucket: 'rocketmq-test-quickstart-cn-north-1'
    template: templates/rocketmq-master.template
  rocketmq-cn-northwest-1-3-AZ:
    parameters:
      AvailabilityZones: cn-northwest-1a,cn-northwest-1b,cn-northwest-1c
      BrokerClusterCount: '1'
      NumberOfAZs: '3'
      RemoteAccessCIDR: '0.0.0.0/0'
      VolumeSize: '100'
      QSS3BucketName: 'rocketmq-deploy-test-minggu'
      QSS3BucketRegion: 'cn-northwest-1'
      QSS3KeyPrefix: 'rocketmq-'
      KeyPairName: 'mongo-db'
      NameServerInstanceType: 'm5.large'
      BrokerNodeInstanceType: 'm5.xlarge'
      NameServerClusterCount: '1'
    regions:
      - cn-northwest-1
    s3_bucket: 'rocketmq-test-quickstart-cn-northwest-1'
    template: templates/rocketmq-master.template
