project:
  name: quickstart-apache-rocketmq
  owner: quickstart-eng@amazon.com
  package_lambda: false
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: 'quickstart-apache-rocketmq'
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
#  - cn-north-1
#  - cn-northwest-1
  s3_bucket: ''
tests:
#  rocketmq-cn-north-1-2-AZ:
#    parameters:
#     AvailabilityZones: $[taskcat_genaz_2]
#     BrokerClusterCount: '1'
#     NumberOfAZs: '2'
#     RemoteAccessCIDR: '0.0.0.0/0'
#     VolumeSize: '100'
#     KeyPairName: $[taskcat_getkeypair]
#     NameServerInstanceType: 'm5.large'
#     BrokerNodeInstanceType: 'm5.xlarge'
#     NameServerClusterCount: '1'
#    regions:
#      - cn-north-1
#    template: templates/rocketmq-entrypoint.template.yaml
#  rocketmq-cn-northwest-1-3-AZ:
#    parameters:
#      AvailabilityZones: $[taskcat_genaz_3]
#      BrokerClusterCount: '1'
#      NumberOfAZs: '3'
#      RemoteAccessCIDR: '0.0.0.0/0'
#      VolumeSize: '100'
#      KeyPairName: $[taskcat_getkeypair]
#      NameServerInstanceType: 'm5.large'
#      BrokerNodeInstanceType: 'm5.xlarge'
#      NameServerClusterCount: '1'
#    regions:
#      - cn-northwest-1
#    template: templates/rocketmq-entrypoint.template.yaml
  rocketmq-us-east-1-3-AZ:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      BrokerClusterCount: '1'
      NumberOfAZs: '3'
      RemoteAccessCIDR: '0.0.0.0/0'
      VolumeSize: '100'
      KeyPairName: $[taskcat_getkeypair]
      NameServerInstanceType: 'm5.large'
      BrokerNodeInstanceType: 'm5.xlarge'
      NameServerClusterCount: '1'
    regions:
      - us-east-1
    template: templates/rocketmq-entrypoint.template.yaml
