// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== 登录您的 AWS 账户

. 使用具有必要权限的 IAM 用户角色在 https://aws.amazon.com 上登录您的 AWS 账户。 有关详细信息，请参阅本指南前面的链接：#_planning_the_deployment[规划部署]。
. 确保您的 AWS 账户配置正确，如链接中所述：#_technical_requirements[技术要求] 部分。

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

此 Quick Start 需要订阅 AWS Marketplace 中 {partner-product-short-name} 的 AMI。

. 登录您的 AWS 账户。
. 打开 {marketplace_listing_url}[{partner-product-short-name} AMI in AWS Marketplace^] 的页面，然后选择 *Continue to Subscribe*。
. 查看软件使用条款和条件，然后选择*接受条款*。 +
将加载确认页面，并向帐户所有者发送电子邮件确认。 有关详细的订阅说明，请参阅 https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace 文档^]。

. 订阅过程完成后，退出 AWS Marketplace，无需进一步操作。 *不要*从 AWS Marketplace 预置软件 - 快速入门会为您部署 AMI。
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start
// 根据您的快速入门调整以下警告。
WARNING: 如果您要将 {partner-product-short-name} 部署到现有 VPC，请确保您的 VPC 在不同可用区中有两个私有子网用于工作负载实例，并且子网未共享。此快速入门不支持 https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[共享子网^]。这些子网需要在其路由表中使用 https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] 以允许实例下载软件包和软件，而不会将它们暴露给互联网。还要确保按照 http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[DHCP 选项集^] 中的说明配置 DHCP 选项中的域名选项。您在启动快速入门时提供 VPC 设置。

每次部署大约需要 {deployment_time} 才能完成。

.登录您的 AWS 账户，然后选择以下选项之一来启动 AWS CloudFormation 模板。有关选择选项的帮助，请参阅本指南前面的链接：#_deployment_options[部署选项]。

[cols=2*]
|===
^|https://fwd.aws/9dXW6[将 {partner-product-short-name} 部署到 AWS 上的新 VPC^]
^|https://aws-quickstart.s3.amazonaws.com/quickstart-apache-rocketmq/templates/rocketmq-entrypoint.template.yaml[View template^]

^|https://fwd.aws/xnNG6[将 {partner-product-short-name} 部署到 AWS 上的现有 VPC^]
^|https://aws-quickstart.s3.amazonaws.com/quickstart-apache-rocketmq/templates/rocketmq.yaml[View template^]
|===

[start=2]
. 检查导航栏右上角显示的 AWS 区域，并根据需要进行更改。 此区域是构建 {partner-product-short-name} 网络基础设施的地方。 默认情况下，模板在 {default_deployment_region} 区域中启动。 有关其他选择，请参阅本指南前面的链接：#_supported_regions[Supported Regions]。

[start=3]
. 在 *Create stack* 页面上，保留模板 URL 的默认设置，然后选择 *Next*。
. 在 *Specify stack details* 页面上，根据需要更改堆栈名称。 查看模板的参数。 为需要输入的参数提供值。 对于所有其他参数，请查看默认设置并根据需要对其进行自定义。 有关每个参数的详细信息，请参阅本指南的链接：#_parameter_reference[参数参考] 部分。 完成查看和自定义参数后，选择 *Next*。



























