// Add any tips or answers to anticipated questions.

== FAQ

*Q.* I encountered a *CREATE_FAILED* error when I launched the Quick Start.

*A.* If AWS CloudFormation fails to create the stack, relaunch the template with *Rollback on failure* set to *Disabled*. This setting is under *Advanced* in the AWS CloudFormation console on the *Configure stack options* page. With this setting, the stack’s state is retained, and the instance keeps running so that you can troubleshoot the issue. (For Windows, look at the log files in `%ProgramFiles%\Amazon\EC2ConfigService` and `C:\cfn\log`.)
// Customize this answer if needed. For example, if you’re deploying on Linux instances, either provide the location for log files on Linux or omit the final sentence. If the Quick Start has no EC2 instances, revise accordingly (something like "and the assets keep running").

WARNING: When you set *Rollback on failure* to *Disabled*, you continue to incur AWS charges for this stack. Delete the stack when you finish troubleshooting.

For more information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^].

*Q.* I encountered a size-limitation error when I deployed the AWS CloudFormation templates.

*A.* Launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location other than an S3 bucket, you might encounter template-size limitations. For more information, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS CloudFormation quotas^].


== Troubleshooting
. I can not access the Apache RocketMQ Web Console, how can I do?
.. First check the ssh tunnel from your desktop to bastion Host is set up correctly. Since Web Console is ran on Nameserver host which is in private subnet, you need the ssh tunnel to bastion host to connect to the Nameserver.
.. If the ssh tunnel is setup correctly but you still can not open the Web Console. The reason should be Web Console process did not start correctly. You need to login to the NameServer and check the install log file at /home/ec2-user/rocketmq-deploy/install.log.
. There is no Apache RocketMQ broker cluster show up in the Web Console, how can I do?
.. Please login to the Broker Node and check the Broker Node install log at /home/ec2-user/rocketmq-deploy/install.log.
.. Fill free to raise an issue in the github repo and attach the error log you find so we can take a look.
. I want to check the Apache RocketMQ internal logs, how can I do?
.. Please go to the sub folder(/home/ec2-user/rocketmq-deploy/) of NameServer node or Broker node to find the internal Apache RocketMQ logs.


